name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/log8100_tp2:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.`2.`5
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Your Heroku API key
          heroku_app_name: log8100-tp2-06  # Your Heroku app name
          heroku_email: ${{ secrets.HEROKU_EMAIL }}  # Your Heroku account email
          heroku_stack: container  # Set the stack to container

