name: Example workflow for Node using Snyk
on: 
  push:                        # Trigger on push events
    branches:
      - main                   # Only trigger on the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
