name: Example workflow for Node using Snyk

on: 
  push:                        
    branches:
      - main                   
      - dev                    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install        
